//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Operations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operations()
        {
            this.MedicalHistory = new HashSet<MedicalHistory>();
        }
    
        public int OperationID { get; set; }
        public string OperationDescription { get; set; }
        public int DoctorID { get; set; }
        public System.DateTime OperationDate { get; set; }
        public int PatientID { get; set; }
        public string OperationResult { get; set; }
        public string OperationImage { get; set; }
        public string PatientSurname { get; set; }
        public string PatientFirstName { get; set; }
        public string PatientPatronymic { get; set; }
        public string DoctorSurname { get; set; }
        public string DoctorFirstName { get; set; }
        public string DoctorPatronymic { get; set; }
        public string currentPatient { get; set; }

        public string DoctorFIO
        {
            get
            {
                return Doctors.DoctorSurname + " " + Doctors.DoctorFirstName + " " + Doctors.DoctorPatronymic;
            }
        }

        public string PatientFIO
        {
            get
            {
                return Patients.PatientSurname + " " + Patients.PatientFirstName + " " + Patients.PatientPatronymic;
            }
        }

        public string OperationDateString
        {
            get
            {
                return OperationDate.ToShortDateString();
            }
        }

        public int OperationCount
        {
            get
            {
                return Convert.ToInt32(HospitalEntities.GetContext().MedicalHistory.Where(x => x.OperationID == OperationID).Count());
            }
        }

        public virtual Doctors Doctors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalHistory> MedicalHistory { get; set; }
        public virtual Patients Patients { get; set; }
        public object currentDoctor { get; internal set; }
    }
}
