//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentSheet
    {
        public int TreatmentID { get; set; }
        public int HistoryID { get; set; }
        public System.DateTime DateOfTreatment { get; set; }
        public string Medicines { get; set; }
        public decimal Temperature { get; set; }
        public string Pressure { get; set; }
        public string PatientsCondition { get; set; }
    
        public virtual MedicalHistory MedicalHistory { get; set; }
    }
}
